# Generated by Django 4.2.3 on 2023-07-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контактные данные', 'verbose_name_plural': 'Контактные данные'},
        ),
    ]
