# Generated by Django 4.2.3 on 2023-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='change_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
