# Generated by Django 4.2.3 on 2023-08-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_change_date_alter_product_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='запрещённое слово')),
            ],
            options={
                'verbose_name': 'слово',
                'verbose_name_plural': 'слова',
            },
        ),
    ]
