# Generated by Django 4.2.3 on 2023-08-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_forbiddenwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forbiddenwords',
            options={'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='номер версии')),
                ('name', models.CharField(max_length=50, verbose_name='название версии')),
                ('is_actual', models.BooleanField(default=False, verbose_name='актуальная версия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Версия продукта',
                'verbose_name_plural': 'Версии продуктов',
            },
        ),
    ]
